### PR TITLE
add support for startkey and endkey.

### PR DESCRIPTION
**Pull request by fiatjaf**

### CODE REVIEW

**Comment by jo** [comment]
Thanks, this is awesome!

Could you please add the options to the README?

**Comment by fiatjaf** [comment]
Should I also update the version number to 1.5.0, build and commit?

**Comment by jo** [comment]
Yes, please!

**Comment by jo** [comment]
Thank you very much, @fiatjaf!

**Comment by jo** [comment]
published `pouchdb-live-query@1.5.0`

**Comment by fiatjaf** [comment]
Thank you very much for merging this!

**Pull request merged**
